"use node";

import { getAuthUserId } from "@convex-dev/auth/server";
import { ConvexError, v } from "convex/values";
import { action, type ActionCtx } from "./_generated/server";
import { internal } from "./_generated/api";
import type { Id } from "./_generated/dataModel";
import webpush from "web-push";

/** Rough sanity check so the admin gets an early, readable error instead of a
 *  redacted "Server Error" from the web-push internals. VAPID keys are base64url
 *  encodings of a P-256 key: 43–44 chars (32 bytes) is the standard size for
 *  keys generated by web-push CLI / push services. */
function keyLooksValid(key: string, kind: "public" | "private"): boolean {
  const clean = key.trim();
  if (!clean) return false;
  if (!/^[A-Za-z0-9_-]+={0,2}$/.test(clean)) return false;
  const bytes = Math.floor((clean.length * 3) / 4);
  if (kind === "private") return bytes === 32;
  return bytes === 32 || bytes === 65;
}

/** Resolve VAPID keys: a VALID env pair wins, otherwise the admin panel keys.
 *  A malformed env key (e.g. a truncated private key pasted into the Freebuff
 *  Keys tab) can no longer shadow the good keys saved in the console. */
async function resolveVapidKeys(
  ctx: ActionCtx,
): Promise<{ publicKey: string; privateKey: string; subject: string }> {
  const fromDb = await ctx.runQuery(internal.push.getVapidKeys, {});
  const envPub = (process.env.VAPID_PUBLIC_KEY ?? "").trim();
  const envPrv = (process.env.VAPID_PRIVATE_KEY ?? "").trim();
  const subject = (process.env.VAPID_SUBJECT ?? "").trim() || "mailto:admin@hopex.site";

  const envPairValid = keyLooksValid(envPub, "public") && keyLooksValid(envPrv, "private");
  const panelPairValid =
    keyLooksValid(fromDb.publicKey, "public") && keyLooksValid(fromDb.privateKey, "private");

  if (envPairValid) return { publicKey: envPub, privateKey: envPrv, subject };
  if (panelPairValid) return { publicKey: fromDb.publicKey, privateKey: fromDb.privateKey, subject };
  // No fully valid pair — fall back to whatever exists so checkVapidSetup can
  // tell the admin exactly which key is bad.
  return {
    publicKey: envPub || fromDb.publicKey,
    privateKey: envPrv || fromDb.privateKey,
    subject,
  };
}

/** Wrap a handler so a plain Error can never leak to the client as a useless
 *  "Server Error Called by client" — production redacts plain Errors, but a
 *  ConvexError always shows its real message. */
function guard(
  fn: (ctx: ActionCtx) => Promise<unknown>,
): (ctx: ActionCtx) => Promise<unknown> {
  return async (ctx) => {
    try {
      return await fn(ctx);
    } catch (e) {
      if (e instanceof ConvexError) throw e;
      const message = e instanceof Error ? e.message : String(e);
      throw new ConvexError(message || "Unknown error");
    }
  };
}

/**
 * Deliver a push payload to a list of subscriptions. Never throws — returns a
 * per-call result so callers (strict adminSendPush, or best-effort broadcast)
 * decide how loud to be. 404/410 subscriptions are dropped automatically.
 */
async function deliverPush(
  ctx: ActionCtx,
  subs: { endpoint: string; p256dh: string; auth: string }[],
  title: string,
  body: string,
  url: string,
): Promise<{ sent: number; failed: number; reason?: string }> {
  const { publicKey, privateKey, subject } = await resolveVapidKeys(ctx);
  if (!publicKey || !privateKey) {
    return {
      sent: 0,
      failed: 0,
      reason:
        "VAPID keys are not set — Admin → Push Broadcast me Public + Private key paste karke Save karein (ya Generate pair dabayen).",
    };
  }
  if (!keyLooksValid(publicKey, "public") || !keyLooksValid(privateKey, "private")) {
    return {
      sent: 0,
      failed: subs.length,
      reason:
        "VAPID key ka format galat hai (private key 43 characters ki honi chahiye). Admin → Push Broadcast me Check setup dabayen — wo exact batayega kaunsa key kharab hai.",
    };
  }
  try {
    webpush.setVapidDetails(subject, publicKey, privateKey);
  } catch (e) {
    return {
      sent: 0,
      failed: subs.length,
      reason: `VAPID keys rejected: ${e instanceof Error ? e.message : String(e)}. Check the keys in Admin → Push Broadcast.`,
    };
  }

  const payload = JSON.stringify({
    title,
    body,
    icon: "/icon-192.png",
    badge: "/icon-192.png",
    data: { url },
  });

  let sent = 0;
  let failed = 0;
  const errorSet = new Set<string>();
  for (const s of subs) {
    try {
      await webpush.sendNotification(
        { endpoint: s.endpoint, keys: { p256dh: s.p256dh, auth: s.auth } },
        payload,
      );
      sent++;
    } catch (err) {
      const code = (err as { statusCode?: number })?.statusCode;
      if (code === 404 || code === 410) {
        try {
          await ctx.runMutation(internal.push.deletePushSubscription, {
            endpoint: s.endpoint,
          });
        } catch {
          /* dropping a dead subscription is best-effort */
        }
        continue;
      }
      failed++;
      const message = err instanceof Error ? err.message : String(err);
      if (message) errorSet.add(message);
    }
  }

  const reason = failed > 0 ? [...errorSet].slice(0, 2).join(" | ") : undefined;
  return { sent, failed, reason };
}

/** Public VAPID key so the browser can subscribe. Served from env or the
 *  admin-managed key pool — no VITE_ duplicate needed. */
export const getVapidPublicKey = action({
  args: {},
  handler: guard(async (ctx) => {
    const { publicKey } = await resolveVapidKeys(ctx);
    return publicKey;
  }),
});

/**
 * Admin: verify the current VAPID setup WITHOUT sending any push. It resolves
 * the keys (env → admin panel), checks their format, and asks web-push to
 * build the request headers — which validates the keys exactly the way a real
 * send would, but makes zero network calls.
 */
export const checkVapidSetup = action({
  args: {},
  handler: guard(async (ctx) => {
    const adminId = await getAuthUserId(ctx);
    if (adminId === null) throw new ConvexError("Not authenticated");
    const isAdmin = await ctx.runQuery(internal.push.isAdmin, { userId: adminId });
    if (!isAdmin) throw new ConvexError("Forbidden");

    const { publicKey, privateKey, subject } = await resolveVapidKeys(ctx);

    const missing = [
      !publicKey ? "public key" : "",
      !privateKey ? "private key" : "",
    ].filter(Boolean);

    if (missing.length > 0) {
      return {
        ok: false,
        error: `Missing ${missing.join(" and ")}. Admin → Push Broadcast me dono keys paste karke Save karein (ya Generate pair dabayen).`,
        publicKeySet: !!publicKey,
        privateKeySet: !!privateKey,
      };
    }

    const bad = [
      !keyLooksValid(publicKey, "public") ? "Public key" : "",
      !keyLooksValid(privateKey, "private") ? "Private key" : "",
    ].filter(Boolean);

    if (bad.length > 0) {
      return {
        ok: false,
        error: `${bad.join(" and ")} ${bad.length > 1 ? "look" : "looks"} invalid. A VAPID private key is 43 characters of base64 (32 bytes). Check that you copied the full key with no extra spaces.`,
        publicKeySet: !!publicKey,
        privateKeySet: !!privateKey,
      };
    }

    try {
      webpush.setVapidDetails(subject, publicKey, privateKey);
      // Build real request headers (no network) — this is where web-push would
      // throw for an unusable key pair.
      webpush.generateRequestDetails({
        endpoint: "https://fcm.googleapis.com/fcm/send/test",
        keys: {
          p256dh: "BM1tR7BzNX6gq1TJ7t9DZKpV1N8r0cQhHkUq9L5O7A0S4fGjXyWbKdEoQzV2mN8tR3uYxw0P6vH",
          auth: "5Mf8vQn0T2rY7cKz",
        },
      } as never);
    } catch (e) {
      const message = e instanceof Error ? e.message : String(e);
      return {
        ok: false,
        error: `Keys were rejected by the push library: ${message.slice(0, 300)}`,
        publicKeySet: true,
        privateKeySet: true,
      };
    }

    return {
      ok: true,
      error: null,
      publicKeySet: true,
      privateKeySet: true,
      source:
        process.env.VAPID_PUBLIC_KEY && process.env.VAPID_PRIVATE_KEY
          ? "environment (Freebuff Keys tab)"
          : "admin panel",
    };
  }),
});

/**
 * Admin: generate a fresh, guaranteed-valid VAPID key pair. Use this when the
 * pasted keys are malformed (the #1 cause of "Server Error" on push). The
 * returned PUBLIC key is what the app/browser must embed to subscribe; the
 * PRIVATE key stays on the server. Saving these replaces the old pair, so any
 * previously subscribed devices must tap Allow once more.
 */
export const generateVapidKeys = action({
  args: {},
  handler: guard(async (ctx) => {
    const adminId = await getAuthUserId(ctx);
    if (adminId === null) throw new ConvexError("Not authenticated");
    const isAdmin = await ctx.runQuery(internal.push.isAdmin, { userId: adminId });
    if (!isAdmin) throw new ConvexError("Forbidden");
    const pair = webpush.generateVAPIDKeys();
    return { publicKey: pair.publicKey, privateKey: pair.privateKey };
  }),
});

/**
 * Admin: send a push notification to subscribed phones — even when the app is
 * closed (web push is delivered by the browser/Android even offline). When
 * `userIds` is omitted it goes to every subscribed device. Every failure is
 * reported as a ConvexError with the REAL reason, and written to the Audit Log
 * so the admin can look up exactly why a send failed.
 */
export const adminSendPush = action({
  args: {
    title: v.string(),
    body: v.string(),
    url: v.optional(v.string()),
    userIds: v.optional(v.array(v.id("users"))),
  },
  handler: guard(async (ctx, args) => {
    const { title, body, url, userIds } = args;

    // 1. Admin check.
    const adminId = await getAuthUserId(ctx);
    if (adminId === null) throw new ConvexError("Not authenticated");
    const isAdmin = await ctx.runQuery(internal.push.isAdmin, { userId: adminId });
    if (!isAdmin) throw new ConvexError("Forbidden");

    // 2. Load the target subscriptions.
    const subs = await ctx.runQuery(internal.push.listSubscriptions, { userIds });
    if (subs.length === 0) {
      throw new ConvexError(
        "No subscriptions found for the selected users. Users must tap Allow notifications first.",
      );
    }

    // 3. Deliver (resolves keys, validates them, sends, drops dead devices).
    const { sent, failed, reason } = await deliverPush(ctx, subs, title, body, url ?? "/dashboard");

    // 4. Audit — never fail the send because the audit log write failed.
    try {
      await ctx.runMutation(internal.push.logAuditPush, {
        adminId,
        detail: `${title} · ${sent} sent / ${failed} failed${reason ? ` · ${reason.slice(0, 200)}` : ""}`,
      });
    } catch {
      /* best-effort audit */
    }

    // 5. Report. If nothing went through, say exactly why (real message,
    //    not a redacted "Server Error").
    if (sent === 0 && (failed > 0 || reason)) {
      throw new ConvexError(reason || "Push failed for unknown reasons.");
    }
    return sent;
  }),
});

/**
 * Admin: broadcast an in-app notification AND — when the selected users have
 * push enabled — a real web/phone push on top (the YouTube-style notification).
 * `userIds` omitted = everyone. The in-app delivery always succeeds; push is
 * best-effort and reports its status in the result so the console can tell the
 * admin if keys/subscriptions are missing.
 */
export const adminBroadcastWithPush = action({
  args: {
    title: v.string(),
    body: v.string(),
    image: v.optional(v.string()),
    kind: v.optional(v.string()),
    popup: v.optional(v.boolean()),
    userIds: v.optional(v.array(v.id("users"))),
    alsoPush: v.optional(v.boolean()),
  },
  handler: guard(async (ctx, args) => {
    const { title, body, image, kind, popup, userIds, alsoPush } = args;

    // 1. Admin check.
    const adminId = await getAuthUserId(ctx);
    if (adminId === null) throw new ConvexError("Not authenticated");
    const isAdmin = await ctx.runQuery(internal.push.isAdmin, { userId: adminId });
    if (!isAdmin) throw new ConvexError("Forbidden");

    // 2. Resolve targets (all users when none chosen).
    const targets: Id<"users">[] =
      userIds && userIds.length > 0 ? userIds : await ctx.runQuery(internal.push.listAllUserIds, {});
    if (targets.length === 0) {
      throw new ConvexError("No users found to notify.");
    }

    // 3. Always create the in-app notifications (bell + optional top popup).
    await ctx.runMutation(internal.notifications.internalBroadcastNotifications, {
      userIds: targets,
      title,
      body,
      kind: kind ?? "info",
      popup: popup ?? false,
      image,
    });

    // 4. Web/phone push — best effort so a missing key never loses the
    //    in-app notification.
    let pushed = 0;
    let pushNote = "";
    if (alsoPush !== false) {
      try {
        const subs = await ctx.runQuery(internal.push.listSubscriptions, {
          userIds: targets,
        });
        if (subs.length > 0) {
          const res = await deliverPush(ctx, subs, title, body, "/dashboard");
          pushed = res.sent;
          if (res.sent === 0 && res.reason) pushNote = res.reason;
        } else {
          pushNote = "Kisi user ne abhi tak notifications Allow nahi ki hain — phone push skip hui.";
        }
      } catch (e) {
        pushNote = e instanceof Error ? e.message.slice(0, 200) : "Push failed";
      }
    }

    // 5. Audit.
    try {
      await ctx.runMutation(internal.push.logAuditPush, {
        adminId,
        detail: `${title} · ${targets.length} notified · ${pushed} pushed${pushNote ? ` · ${pushNote.slice(0, 200)}` : ""}`,
      });
    } catch {
      /* best-effort audit */
    }

    return { notified: targets.length, pushed, pushNote };
  }),
});
