"use node";

import { getAuthUserId } from "@convex-dev/auth/server";
import { ConvexError, v } from "convex/values";
import { action, type ActionCtx } from "./_generated/server";
import { internal } from "./_generated/api";
import webpush from "web-push";

/** Resolve VAPID keys: env vars first, then the admin-managed key pool. */
async function resolveVapidKeys(
  ctx: ActionCtx,
): Promise<{ publicKey: string; privateKey: string; subject: string }> {
  const fromDb = await ctx.runQuery(internal.push.getVapidKeys, {});
  return {
    publicKey: (process.env.VAPID_PUBLIC_KEY ?? "").trim() || fromDb.publicKey,
    privateKey: (process.env.VAPID_PRIVATE_KEY ?? "").trim() || fromDb.privateKey,
    subject:
      (process.env.VAPID_SUBJECT ?? "").trim() || "mailto:admin@hopex.site",
  };
}

/** Rough sanity check so the admin gets an early, readable error instead of a
 *  redacted "Server Error" from the web-push internals. VAPID keys are base64url
 *  encodings of a P-256 key: 43–44 chars (32 bytes) is the standard size for
 *  keys generated by web-push CLI / push services. */
function keyLooksValid(key: string, kind: "public" | "private"): boolean {
  const clean = key.trim();
  if (!/^[A-Za-z0-9_-]+={0,2}$/.test(clean)) return false;
  const bytes = Math.floor((clean.length * 3) / 4);
  if (kind === "private") return bytes === 32;
  return bytes === 32 || bytes === 65;
}

/** Public VAPID key so the browser can subscribe. Served from env or the
 *  admin-managed key pool — no VITE_ duplicate needed. */
export const getVapidPublicKey = action({
  args: {},
  handler: async (ctx) => {
    const { publicKey } = await resolveVapidKeys(ctx);
    return publicKey;
  },
});

/**
 * Admin: verify the current VAPID setup WITHOUT sending any push. It resolves
 * the keys (env → admin panel), checks their format, and asks web-push to
 * build the request headers — which validates the keys exactly the way a real
 * send would, but makes zero network calls. Returns a clear status the console
 * can render as green/red.
 */
export const checkVapidSetup = action({
  args: {},
  handler: async (ctx) => {
    const adminId = await getAuthUserId(ctx);
    if (adminId === null) throw new ConvexError("Not authenticated");
    const isAdmin = await ctx.runQuery(internal.push.isAdmin, { userId: adminId });
    if (!isAdmin) throw new ConvexError("Forbidden");

    const { publicKey, privateKey, subject } = await resolveVapidKeys(ctx);

    const missing = [
      !publicKey ? "VAPID_PUBLIC_KEY" : "",
      !privateKey ? "VAPID_PRIVATE_KEY" : "",
    ].filter(Boolean);

    if (missing.length > 0) {
      return {
        ok: false,
        error: `Missing ${missing.join(" and ")}. Paste both keys in this panel (or set them in the Freebuff Keys tab).`,
        publicKeySet: !!publicKey,
        privateKeySet: !!privateKey,
      };
    }

    const bad = [
      !keyLooksValid(publicKey, "public") ? "Public key" : "",
      !keyLooksValid(privateKey, "private") ? "Private key" : "",
    ].filter(Boolean);

    if (bad.length > 0) {
      return {
        ok: false,
        error: `${bad.join(" and ")} ${bad.length > 1 ? "look" : "looks"} invalid. A VAPID key is 43 characters of base64 (like BLU…9A=). Check that you copied the full key with no extra spaces.`,
        publicKeySet: true,
        privateKeySet: true,
      };
    }

    try {
      webpush.setVapidDetails(subject, publicKey, privateKey);
      // Build real request headers (no network) — this is where web-push would
      // throw for an unusable key pair.
      webpush.generateRequestDetails({
        endpoint: "https://fcm.googleapis.com/fcm/send/test",
        keys: {
          p256dh: "BM1tR7BzNX6gq1TJ7t9DZKpV1N8r0cQhHkUq9L5O7A0S4fGjXyWbKdEoQzV2mN8tR3uYxw0P6vH",
          auth: "5Mf8vQn0T2rY7cKz",
        },
      } as never);
    } catch (e) {
      const message = e instanceof Error ? e.message : String(e);
      return {
        ok: false,
        error: `Keys were rejected by the push library: ${message.slice(0, 300)}`,
        publicKeySet: true,
        privateKeySet: true,
      };
    }

    return {
      ok: true,
      error: null,
      publicKeySet: true,
      privateKeySet: true,
      source: process.env.VAPID_PUBLIC_KEY ? "environment (Keys tab)" : "admin panel",
    };
  },
});

/**
 * Admin: generate a fresh, guaranteed-valid VAPID key pair. Use this when the
 * pasted keys are malformed (the #1 cause of "Server Error" on push). The
 * returned PUBLIC key is what the app/browser must embed to subscribe; the
 * PRIVATE key stays on the server. Saving these replaces the old pair, so any
 * previously subscribed devices must tap Allow once more.
 */
export const generateVapidKeys = action({
  args: {},
  handler: async (ctx) => {
    const adminId = await getAuthUserId(ctx);
    if (adminId === null) throw new ConvexError("Not authenticated");
    const isAdmin = await ctx.runQuery(internal.push.isAdmin, { userId: adminId });
    if (!isAdmin) throw new ConvexError("Forbidden");
    const pair = webpush.generateVAPIDKeys();
    return { publicKey: pair.publicKey, privateKey: pair.privateKey };
  },
});

/**
 * Admin: send a push notification to subscribed phones — even when the app is
 * closed (web push is delivered by the browser/Android even offline). When
 * `userIds` is omitted it goes to every subscribed device.
 *
 * Every failure path throws ConvexError with the REAL reason (production
 * deployments redact plain Errors to a generic "Server Error").
 */
export const adminSendPush = action({
  args: {
    title: v.string(),
    body: v.string(),
    url: v.optional(v.string()),
    userIds: v.optional(v.array(v.id("users"))),
  },
  handler: async (ctx, { title, body, url, userIds }) => {
    // 1. Admin check — auth is available directly on the action context; the
    //    role lookup runs as a plain DB read (no auth dependency).
    const adminId = await getAuthUserId(ctx);
    if (adminId === null) throw new ConvexError("Not authenticated");
    const isAdmin = await ctx.runQuery(internal.push.isAdmin, { userId: adminId });
    if (!isAdmin) throw new ConvexError("Forbidden");

    // 2. Resolve the VAPID keys (env → admin panel).
    const { publicKey, privateKey, subject } = await resolveVapidKeys(ctx);
    if (!publicKey || !privateKey) {
      throw new ConvexError(
        "VAPID keys are not set. Open Admin → Push Broadcast, paste both keys into the setup card and press Save (or set VAPID_PUBLIC_KEY / VAPID_PRIVATE_KEY in the Freebuff Keys tab).",
      );
    }

    // 3. Load the target subscriptions.
    const subs = await ctx.runQuery(internal.push.listSubscriptions, { userIds });
    if (subs.length === 0) {
      throw new ConvexError(
        "No subscriptions found for the selected users. Users must tap Allow notifications in the app first.",
      );
    }

    // 4. Validate the key pair exactly like a real send would (throws with the
    //    real reason for malformed keys — previously this surfaced as a
    //    useless "Server Error").
    try {
      webpush.setVapidDetails(subject, publicKey, privateKey);
    } catch (e) {
      throw new ConvexError(
        `VAPID keys were rejected: ${e instanceof Error ? e.message : String(e)}. Check the keys in Admin → Push Broadcast.`,
      );
    }

    const payload = JSON.stringify({
      title,
      body,
      icon: "/icon-192.png",
      badge: "/icon-192.png",
      data: { url: url ?? "/dashboard" },
    });

    // 5. Send to each device. 404/410 means the subscription is dead — drop it.
    //    Other failures are collected so a single bad device can't mask a
    //    genuine key/network problem.
    let sent = 0;
    let failed = 0;
    const errorSet = new Set<string>();
    for (const s of subs) {
      try {
        await webpush.sendNotification(
          { endpoint: s.endpoint, keys: { p256dh: s.p256dh, auth: s.auth } },
          payload,
        );
        sent++;
      } catch (err) {
        const code = (err as { statusCode?: number })?.statusCode;
        if (code === 404 || code === 410) {
          try {
            await ctx.runMutation(internal.push.deletePushSubscription, {
              endpoint: s.endpoint,
            });
          } catch {
            /* dropping a dead subscription is best-effort */
          }
          continue;
        }
        failed++;
        const message = err instanceof Error ? err.message : String(err);
        if (message) errorSet.add(message);
      }
    }

    // 6. Audit — never fail the send because the audit log write failed.
    try {
      await ctx.runMutation(internal.push.logAuditPush, {
        adminId,
        detail: `${title} · ${sent} sent / ${failed} failed`,
      });
    } catch {
      /* best-effort audit */
    }

    // 7. Report. If nothing went through, say exactly why (real message,
    //    not a redacted "Server Error").
    if (sent === 0 && failed > 0) {
      const reasons = [...errorSet].slice(0, 3).join(" | ");
      throw new ConvexError(
        `Push failed for ${failed} device(s). ${reasons || "Unknown error"}`,
      );
    }
    return sent;
  },
});
